(function() {var implementors = {};
implementors["pyo3"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"pyo3/class/methods/struct.PyMethodDef.html\" title=\"struct pyo3::class::methods::PyMethodDef\">PyMethodDef</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"pyo3/ffi/struct.PyMethodDef.html\" title=\"struct pyo3::ffi::PyMethodDef\">PyMethodDef</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"pyo3/class/methods/struct.PyGetterDef.html\" title=\"struct pyo3::class::methods::PyGetterDef\">PyGetterDef</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"pyo3/class/methods/struct.PySetterDef.html\" title=\"struct pyo3::class::methods::PySetterDef\">PySetterDef</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"pyo3/ffi/struct.PyGetSetDef.html\" title=\"struct pyo3::ffi::PyGetSetDef\">PyGetSetDef</a>","impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"pyo3/struct.Py.html\" title=\"struct pyo3::Py\">Py</a>&lt;T&gt;","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"pyo3/struct.PyObject.html\" title=\"struct pyo3::PyObject\">PyObject</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"pyo3/buffer/struct.PyBuffer.html\" title=\"struct pyo3::buffer::PyBuffer\">PyBuffer</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
